-- Code generated by BobGen psql v0.40.2. DO NOT EDIT.
-- This file is meant to be re-generated in place and/or deleted at any time.

-- FindUserByEmail
SELECT "users"."id" AS "id", "users"."email" AS "email", "users"."username" AS "username", "users"."full_name" AS "full_name", "users"."created_at" AS "created_at", "users"."last_login" AS "last_login", "users"."is_active" AS "is_active" FROM users WHERE email = $1;
